version: '3.8'

services:
  mongo:
    image: mongo
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo_data:/data/db
  backend:
    image: my_app_backend_prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/the_database
      - PORT=3003
      - SECRET=yoursecret
    depends_on:
      - mongo
  frontend:
    image: my_app_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    expose:
      - 80
    depends_on:
      - backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend
